on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
      - name: Build
        run: hugo --minify -s folio
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: e5e97876a3731c565acf1061ef89067f
          projectName: folio-hugo
          directory: public
          workingDirectory: folio
